### ISSUE TITLE
does not build on CentOS7, due to newer GCC 4.7

### ISSUE THREAD

**Issue by tpokorra** [tpokorra/lbs-nsis#1]
see compiler error below.
See "name lookup changes" in https://gcc.gnu.org/gcc-4.7/porting_to.html
solution: use parameter -fpermissive for the moment

```
[00201] g++ -o build/release/makensis/script.o -c -Wno-non-virtual-dtor -Wall -O2 -m32 "-DNSISCALL= __attribute__((__stdcall__))" -D_WIN32_IE=0x0500 -Ibuild/release/config Source/script.cpp
[00202] In file included from Source/script.cpp:22:0:
[00202] Source/util.h: In instantiation of 'void __free_with_close::operator()(T&) [with T = int]':
[00202] Source/util.h:114:32:   required from 'ResourceManager<_RESOURCE, _FREE_RESOURCE>::~ResourceManager() [with _RESOURCE = int; _FREE_RESOURCE = __free_with_close]'
[00202] Source/script.cpp:6460:1:   required from here
[00202] Source/util.h:128:59: error: 'close' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
[00202]    template <typename T> void operator()(T& x) { freefunc(x); } \
[00202]                                                            ^
[00202] Source/util.h:145:1: note: in expansion of macro 'RM_DEFINE_FREEFUNC'
[00202]  RM_DEFINE_FREEFUNC(close);
[00202]  ^
[00202] In file included from Source/script.cpp:46:0:
[00202] /usr/include/unistd.h:353:12: note: 'int close(int)' declared here, later in the translation unit
[00202]  extern int close (int __fd);
[00202]             ^
[00202] scons: *** [build/release/makensis/script.o] Error 1
[00202] scons: building terminated because of errors.
[00202] error: Bad exit status from /var/tmp/rpm-tmp.vu2aoz (%build)
```
